# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-22 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('drchrono_id', models.IntegerField(unique=True)),
                ('drchrono_practice_group_id', models.IntegerField()),
                ('social_auth', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to='social_django.UserSocialAuth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
