# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-24 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_waited',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
